service: ws-signal
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  region: ap-northeast-1
  websocketsApiName: ${self:service}__${sls:stage}__ws-signal-server
  websocketsApiRouteSelectionExpression: $request.body.action
  environment:
    SERVICE: ${self:service}
    STAGE: ${sls:stage}
    WEBSOCKET_API_ID:
      Ref: WebsocketsApi

functions:
  ping:
    handler: src/ping.ping
    events:
      - websocket:
          route: ping
