service: gbraver-burst-ws-signal
frameworkVersion: "4"

custom:
  connections: ${self:service}__${sls:stage}__connections
  room: ${self:service}__${sls:stage}__room

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  region: ap-northeast-1
  tracing:
    apiGateway: true
    lambda: true
  websocketsApiName: ${self:service}__${sls:stage}__ws-signal-server
  websocketsApiRouteSelectionExpression: $request.body.action
  environment:
    SERVICE: ${self:service}
    STAGE: ${sls:stage}
    WEBSOCKET_API_ID:
      Ref: WebsocketsApi
    DYNAMODB_CONNECTIONS_TABLE: ${self:custom.connections}
    DYNAMODB_ROOM_TABLE: ${self:custom.room}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "xray:PutTraceSegments"
            - "xray:PutTelemetryRecords"
          Resource: "*"
        - Effect: Allow
          Action:
            - "execute-api:ManageConnections"
          Resource:
            - "arn:aws:execute-api:*:*:**/@connections/*"
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Query"
            - "dynamodb:Scan"
            - "dynamodb:BatchWrite*"
          Resource:
            - Fn::GetAtt: [ConnectionsTable, Arn]

functions:
  connect:
    handler: src/connect.connect
    events:
      - websocket:
          route: $connect
  disconnect:
    handler: src/disconnect.disconnect
    events:
      - websocket:
          route: $disconnect
  ping:
    handler: src/ping.ping
    events:
      - websocket:
          route: ping
  createRoom:
    handler: src/create-room.createRoom
    events:
      - websocket:
          route: create-room

resources:
  Resources:
    ConnectionsTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:custom.connections}
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    RoomTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:custom.room}
        AttributeDefinitions:
          - AttributeName: roomID
            AttributeType: S
        KeySchema:
          - AttributeName: roomID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
