version: 0.2
env:
  # プロジェクト実行時に、環境変数STAGEに削除したいステージ名を指定する
  parameter-store:
    SERVICE: /GbraverBurst/dev/service
    VPC_SUBNET_COUNT: /GbraverBurst/dev/vpcSubnetCount
phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - ./backend-ecs-remove.sh