version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - cd packages/backend-ecs/
      - npm ci
      - npm run deploy