version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - cd packages/backend-ecs/
      - npm ci
      - export MATCH_MAKE_ECR_TAG=`git rev-parse HEAD`
      - npm run deploy