version: 0.2
env:
  # variables:
  #   COTURN_SHARED_SECRET: /GbraverBurst/prod/coturnSharedSecret #あいことば対戦を本番リリースするまでコメントアウト
  parameter-store:
    SERVICE: /GbraverBurst/prod/service
    # WS_SIGNAL_SERVICE: /GbraverBurst/prod/wsSignalService
    STAGE: /GbraverBurst/prod/stage
    WS_API_DOMAIN_NAME: /GbraverBurst/prod/wsApiDomainName
    WS_API_CERT_ARN: /GbraverBurst/prod/wsApiCertArn
    # WS_SIGNAL_DOMAIN_NAME: /GbraverBurst/prod/wsSignalDomainName #あいことば対戦を本番リリースするまでコメントアウト
    # WS_SIGNAL_CERT_ARN: /GbraverBurst/prod/wsSignalCertArn #あいことば対戦を本番リリースするまでコメントアウト
    # WEBRTC_HELPER_DOMAIN_NAME: /GbraverBurst/prod/webrtcHelperDomainName #あいことば対戦を本番リリースするまでコメントアウト
    # WEBRTC_HELPER_CERT_ARN: /GbraverBurst/prod/webrtcHelperCertArn #あいことば対戦を本番リリースするまでコメントアウト
    # ANONYMOUS_BACKEND_CORS_ORIGIN: /GbraverBurst/prod/webrtcHelperCorsOrigin #あいことば対戦を本番リリースするまでコメントアウト
    COGNITO_USER_POOL_ID: /GbraverBurst/prod/cognitoUserPoolId
    COGNITO_CLIENT_ID: /GbraverBurst/prod/cognitoClientId
    DOCKER_USER: /GbraverBurst/prod/dockerUser
    DOCKER_TOKEN: /GbraverBurst/prod/dockerToken
    MATCH_MAKE_ECR_REPOSITORY_NAME: /GbraverBurst/prod/matchMakeEcrRepositoryName
    VPC_SUBNET_COUNT: /GbraverBurst/prod/vpcSubnetCount
    SERVERLESS_ACCESS_KEY: /GbraverBurst/prod/serverlessAccessKey
phases:
  install:
    runtime-versions:
      nodejs: 24
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - DOCKER_IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - ./deploy-serverless.bash
      - ./push-match-make-container.bash
      - ./deploy-backend-ecs.bash
      # - ./deploy-ws-signal.bash #あいことば対戦を本番リリースするまでコメントアウト
