version: 0.2
env:
  # プロジェクト実行時に、環境変数STAGEに削除したいステージ名を指定する
  parameter-store:
    WS_SIGNAL_SERVICE: /GbraverBurst/dev/wsSignalService
    WS_SIGNAL_DOMAIN_NAME: /GbraverBurst/dev/wsSignalDomainName
    WS_SIGNAL_CERT_ARN: /GbraverBurst/dev/wsSignalCertArn
    WEBRTC_HELPER_DOMAIN_NAME: /GbraverBurst/dev/webrtcHelperDomainName
    WEBRTC_HELPER_CERT_ARN: /GbraverBurst/dev/webrtcHelperCertArn
    WEBRTC_HELPER_CORS_ORIGINS: /GbraverBurst/dev/webrtcHelperCorsOrigins
    SERVERLESS_ACCESS_KEY: /GbraverBurst/dev/serverlessAccessKey
phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - ./remove-ws-signal.bash
