version: 0.2
env:
  parameter-store:
    SERVICE: /GbraverBurst/dev/service
    STAGE: /GbraverBurst/dev/stage
    WS_API_DOMAIN_NAME: /GbraverBurst/dev/wsApiDomainName
    WS_API_CERT_ARN: /GbraverBurst/dev/wsApiCertArn
    COGNITO_USER_POOL_ID: /GbraverBurst/dev/cognitoUserPoolId
    COGNITO_CLIENT_ID: /GbraverBurst/dev/cognitoClientId
    DOCKER_USER: /GbraverBurst/dev/dockerUser
    DOCKER_TOKEN: /GbraverBurst/dev/dockerToken
    MATCH_MAKE_ECR_REPOSITORY_NAME: /GbraverBurst/dev/matchMakeEcrRepositoryName
    VPC_SUBNET_COUNT: /GbraverBurst/dev/vpcSubnetCount
    SERVERLESS_ACCESS_KEY: /GbraverBurst/dev/serverlessAccessKey
phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - ./deploy-serverless.bash
