version: 0.2
env:
  parameter-store:
    SERVICE: /GbraverBurst/prod/service
    STAGE: /GbraverBurst/prod/stage
    WS_API_DOMAIN_NAME: /GbraverBurst/prod/wsApiDomainName
    WS_API_CERT_ARN: /GbraverBurst/prod/wsApiCertArn
    COGNITO_USER_POOL_ID: /GbraverBurst/prod/cognitoUserPoolId
    COGNITO_CLIENT_ID: /GbraverBurst/prod/cognitoClientId
    DOCKER_USER: /GbraverBurst/prod/dockerUser
    DOCKER_TOKEN: /GbraverBurst/prod/dockerToken
    MATCH_MAKE_ECR_REPOSITORY_NAME: /GbraverBurst/prod/matchMakeEcrRepositoryName
    VPC_SUBNET_COUNT: /GbraverBurst/prod/vpcSubnetCount
    SERVERLESS_ACCESS_KEY: /GbraverBurst/prod/serverlessAccessKey
phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - DOCKER_IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - ./deploy-serverless.bash
      - ./push-match-make-container.bash
      - ./deploy-backend-ecs.bash
