version: 0.2
# プロジェクト実行時に、環境変数STAGEに削除したいステージ名を指定する
env:
  variables:
    COTURN_SHARED_SECRET: /GbraverBurst/dev/coturnSharedSecret
  parameter-store:
    ANONYMOUS_SERVICE: /GbraverBurst/dev/anonymousService
    WS_SIGNAL_DOMAIN_NAME: /GbraverBurst/dev/wsSignalDomainName
    WS_SIGNAL_CERT_ARN: /GbraverBurst/dev/wsSignalCertArn
    ANONYMOUS_BACKEND_CORS_ORIGIN: /GbraverBurst/dev/anonymousBackendCorsOrigin
    SERVERLESS_ACCESS_KEY: /GbraverBurst/dev/serverlessAccessKey
phases:
  install:
    runtime-versions:
      nodejs: 24
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - ./remove-anonymous.bash
