version: 0.2
env:
  parameter-store:
    SERVICE: /GbraverBurst/dev/service
    ALLOW_ORIGIN: /GbraverBurst/dev/allowOrigin
    TEST_ALLOW_ORIGIN: /GbraverBurst/dev/testAllowOrigin
    DOCKER_USER: /GbraverBurst/dev/dockerUser
    DOCKER_TOKEN: /GbraverBurst/dev/dockerToken
    MATCH_MAKE_ECR_REPOSITORY_NAME: /GbraverBurst/dev/matchMakeEcrRepositoryName
    VPC_SUBNET_COUNT: /GbraverBurst/dev/vpcSubnetCount
phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - DOCKER_IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - ./push-match-make-container.bash
      - ./deploy-backend-ecs.bash
