version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - npm run bootstrap
      - npm run build:core
      - npm run build:serverless
      - npm run deploy:serverless