version: 0.2
env:
  parameter-store:
    SERVICE: /GbraverBurst/prod/service
    STAGE: /GbraverBurst/prod/stage
    ALLOW_ORIGIN: /GbraverBurst/prod/allowOrigin
    TEST_ALLOW_ORIGIN: /GbraverBurst/prod/testAllowOrigin
    COGNITO_JWKS_URL: /GbraverBurst/prod/auth0JwksUrl
    COGNITO_AUDIENCE: /GbraverBurst/prod/auth0Audience
    DOCKER_USER: /GbraverBurst/prod/dockerUser
    DOCKER_TOKEN: /GbraverBurst/prod/dockerToken
    MATCH_MAKE_ECR_REPOSITORY_NAME: /GbraverBurst/prod/matchMakeEcrRepositoryName
    VPC_SUBNET_COUNT: /GbraverBurst/prod/vpcSubnetCount
    SERVERLESS_ACCESS_KEY: /GbraverBurst/prod/serverlessAccessKey
phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - DOCKER_IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - ./deploy-serverless.bash
      - ./push-match-make-container.bash
      - ./deploy-backend-ecs.bash