version: 0.2
# プロジェクト実行時に、環境変数STAGEに削除したいステージ名を指定する
env:
  variables:
    COTURN_SHARED_SECRET: /GbraverBurst/prod/coturnSharedSecret
  parameter-store:
    WS_SIGNAL_SERVICE: /GbraverBurst/prod/wsSignalService
    WS_SIGNAL_DOMAIN_NAME: /GbraverBurst/prod/wsSignalDomainName
    WS_SIGNAL_CERT_ARN: /GbraverBurst/prod/wsSignalCertArn
    WEBRTC_HELPER_DOMAIN_NAME: /GbraverBurst/prod/webrtcHelperDomainName
    WEBRTC_HELPER_CERT_ARN: /GbraverBurst/prod/webrtcHelperCertArn
    WEBRTC_HELPER_CORS_ORIGIN: /GbraverBurst/prod/webrtcHelperCorsOrigin
    SERVERLESS_ACCESS_KEY: /GbraverBurst/prod/serverlessAccessKey
phases:
  install:
    runtime-versions:
      nodejs: 24
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - ./remove-ws-signal.bash
