version: 0.2
env:
  parameter-store:
    SERVICE: /GbraverBurst/dev/service
    STAGE: /GbraverBurst/dev/stage
    ALLOW_ORIGIN: /GbraverBurst/dev/allowOrigin
    TEST_ALLOW_ORIGIN: /GbraverBurst/dev/testAllowOrigin
    COGNITO_USER_POOL_ID: /GbraverBurst/dev/auth0JwksUrl
    COGNITO_CLIENT_ID: /GbraverBurst/dev/auth0Audience
    DOCKER_USER: /GbraverBurst/dev/dockerUser
    DOCKER_TOKEN: /GbraverBurst/dev/dockerToken
    MATCH_MAKE_ECR_REPOSITORY_NAME: /GbraverBurst/dev/matchMakeEcrRepositoryName
    VPC_SUBNET_COUNT: /GbraverBurst/dev/vpcSubnetCount
    SERVERLESS_ACCESS_KEY: /GbraverBurst/dev/serverlessAccessKey
phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - DOCKER_IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - ./deploy-serverless.bash
      - ./push-match-make-container.bash
      - ./deploy-backend-ecs.bash