version: 0.2
env:
  parameter-store:
    SERVICE: /GbraverBurst/prod/service
    STAGE: /GbraverBurst/prod/stage
    ALLOW_ORIGIN: /GbraverBurst/prod/allowOrigin
    TEST_ALLOW_ORIGIN: /GbraverBurst/prod/testAllowOrigin
    AUTH0_DOMAIN: /GbraverBurst/prod/auth0Domain
    AUTH0_JWKS_URL: /GbraverBurst/prod/auth0JwksUrl
    AUTH0_AUDIENCE: /GbraverBurst/prod/auth0Audience
    AUTH0_USER_MANAGEMENT_APP_CLIENT_ID: /GbraverBurst/prod/auth0UserManagementAppClientId
    AUTH0_USER_MANAGEMENT_APP_CLIENT_SECRET: /GbraverBurst/prod/auth0UserManagementAppClientSecret
    DOCKER_USER: /GbraverBurst/prod/dockerUser
    DOCKER_TOKEN: /GbraverBurst/prod/dockerToken
    MATCH_MAKE_ECR_REPOSITORY_NAME: /GbraverBurst/prod/matchMakeEcrRepositoryName
    VPC_SUBNET_COUNT: /GbraverBurst/prod/vpcSubnetCount
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm ci
      - npm run bootstrap
  build:
    commands:
      - DOCKER_IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - npm run build
      - ./serverless-deploy.sh
      - ./match-make-container-push.sh
      - ./backend-ecs-deploy.sh