version: 0.2
# プロジェクト実行時に、環境変数STAGEに削除したいステージ名を指定する
env:
  variables:
    COTURN_SHARED_SECRET: /GbraverBurst/dev/coturnSharedSecret
  parameter-store:
    WS_SIGNAL_SERVICE: /GbraverBurst/dev/wsSignalService
    WS_SIGNAL_DOMAIN_NAME: /GbraverBurst/dev/wsSignalDomainName
    WS_SIGNAL_CERT_ARN: /GbraverBurst/dev/wsSignalCertArn
    BACKEND_CLOUDFRONT_DOMAIN_NAME: /GbraverBurst/dev/backendCloudFrontDomainName
    BACKEND_CLOUDFRONT_CERT_ARN: /GbraverBurst/dev/backendCloudFrontCertArn
    WEBRTC_HELPER_CORS_ORIGIN: /GbraverBurst/dev/webrtcHelperCorsOrigin
    SERVERLESS_ACCESS_KEY: /GbraverBurst/dev/serverlessAccessKey
phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - ./remove-ws-signal.bash
