version: 0.2
env:
  parameter-store:
    SERVICE: /GbraverBurst/dev/service
    STAGE: /GbraverBurst/dev/stage
    ALLOW_ORIGIN: /GbraverBurst/dev/allowOrigin
    TEST_ALLOW_ORIGIN: /GbraverBurst/dev/testAllowOrigin
    AUTH0_DOMAIN: /GbraverBurst/dev/auth0Domain
    AUTH0_JWKS_URL: /GbraverBurst/dev/auth0JwksUrl
    AUTH0_AUDIENCE: /GbraverBurst/dev/auth0Audience
    AUTH0_USER_MANAGEMENT_APP_CLIENT_ID: /GbraverBurst/dev/auth0UserManagementAppClientId
    AUTH0_USER_MANAGEMENT_APP_CLIENT_SECRET: /GbraverBurst/dev/auth0UserManagementAppClientSecret
    DOCKER_USER: /GbraverBurst/dev/dockerUser
    DOCKER_TOKEN: /GbraverBurst/dev/dockerToken
    MATCH_MAKE_ECR_REPOSITORY_NAME: /GbraverBurst/dev/matchMakeEcrRepositoryName
    VPC_SUBNET_COUNT: /GbraverBurst/dev/vpcSubnetCount
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - npm ci
      - npm run bootstrap
  build:
    commands:
      - npm run build
      - ./serverless-deploy.sh
      - ./match-make-container-push.sh
      - ./backend-ecs-deploy.sh