version: 0.2
env:
  parameter-store:
    STAGE: /GbraverBurst/dev/stage
    DOCKER_USER: /GbraverBurst/dev/dockerUser
    DOCKER_TOKEN: /GbraverBurst/dev/dockerToken
    MATCH_MAKE_ECR_REPOSITORY_NAME: /GbraverBurst/dev/matchMakeEcrRepositoryName
phases:
  install:
    runtime-versions:
      nodejs: 16
  build:
    commands:
      - ./match-make-container-push.sh