version: 0.2
env:
  # プロジェクト実行時に、環境変数STAGEに削除したいステージ名を指定する
  parameter-store:
    SERVICE: /GbraverBurst/prod/service
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - ./serverless-remove.sh