version: 0.2
env:
  parameter-store:
    SERVICE: /GbraverBurst/dev/service
    STAGE: /GbraverBurst/dev/stage
    AUTH0_JWKS_URL: /GbraverBurst/dev/auth0JwksUrl
    AUTH0_AUDIENCE: /GbraverBurst/dev/auth0Audience
phases:
  build:
    commands:
      - ./serverless-deploy.sh