version: 0.2
env:
  parameter-store:
    SERVICE: /GbraverBurst/prod/service
    STAGE: /GbraverBurst/prod/stage
    ALLOW_ORIGIN: /GbraverBurst/prod/allowOrigin
    TEST_ALLOW_ORIGIN: /GbraverBurst/prod/testAllowOrigin
    AUTH0_DOMAIN: /GbraverBurst/prod/auth0Domain
    AUTH0_JWKS_URL: /GbraverBurst/prod/auth0JwksUrl
    AUTH0_AUDIENCE: /GbraverBurst/prod/auth0Audience
    AUTH0_USER_MANAGEMENT_APP_CLIENT_ID: /GbraverBurst/prod/auth0UserManagementAppClientId
    AUTH0_USER_MANAGEMENT_APP_CLIENT_SECRET: /GbraverBurst/prod/auth0UserManagementAppClientSecret
phases:
  build:
    commands:
      - ./serverless-deploy.sh