service: gbraver-burst-serverless
frameworkVersion: '2'
useDotenv: true

custom:
  gbraverBurstConnections: gbraver_burst_connections
  casualMatchEntries: casual_match_entries

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  lambdaHashingVersion: 20201221
  websocketsApiName: gbraver-burst-ws-api
  websocketsApiRouteSelectionExpression: $request.body.action
  #apiGateway:
  #  websocketApiId:
  #    Fn::GetAtt: [GbraverBurstWebsocket, ApiEndpoint]
  environment:
    GBRAVER_BURST_CONNECTIONS: ${self:custom.gbraverBurstConnections}
    CASUAL_MATCH_ENTRIES: ${self:custom.casualMatchEntries}
    AUTH0_JWKS_URL: ${env:AUTH0_JWKS_URL}
    AUTH0_AUDIENCE: ${env:AUTH0_AUDIENCE}
    TEST_API_ID:
      Ref: GbraverBurstWebsocket
    TEST_API_ENDPOINT:
      Fn::GetAtt: [GbraverBurstWebsocket, ApiEndpoint]

  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'dynamodb:PutItem'
        - 'dynamodb:GetItem'
        - 'dynamodb:DeleteItem'
        - 'dynamodb:Scan'
        - 'dynamodb:BatchWrite*'
      Resource:
        - Fn::GetAtt: [GbraverBurstConnectionsTable, Arn]
        - Fn::GetAtt: [CasualMatchEntriesTable, Arn]
    - Effect: Allow
      Action:
        - 'execute-api:ManageConnections'
      Resource:
        - 'arn:aws:execute-api:*:*:**/@connections/*'

functions:
  auth:
    handler: src/handler.authorizer
  connect:
    handler: src/handler.connect
    events:
      - websocket:
          route: $connect
          authorizer:
            name: auth
            identitySource:
              - 'route.request.querystring.token'
  disconnect:
    handler: src/handler.disconnect
    events:
      - websocket:
          route: $disconnect
  ping:
    handler: src/handler.ping
    events:
      - websocket:
          route: ping
  enterCasualMatch:
    handler: src/handler.enterCasualMatch
    events:
      - websocket:
          route: enterCasualMatch
  pollingCasualMatchEntries:
    handler: src/handler.pollingCasualMatchEntries
    events:
      - schedule: rate(1 minute)

resources:
  Resources:
    GbraverBurstWebsocket:
      Type: 'AWS::ApiGatewayV2::Api'
      Properties:
        Name: gbraver-burst-ws
        ProtocolType: WEBSOCKET
        RouteSelectionExpression: '$request.body.action'
    GbraverBurstConnectionsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.gbraverBurstConnections}
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    CasualMatchEntriesTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.casualMatchEntries}
        AttributeDefinitions:
          - AttributeName: userID
            AttributeType: S
        KeySchema:
          - AttributeName: userID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1