name: Node.js CI
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
env:
  NODE_JS_VERSION: 18.x
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_JS_VERSION }}
    - run: npm ci
    - run: npm run lint
    - run: npm run detect-circular
    - run: npm test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_JS_VERSION }}
      - run: npm ci
      - run: npm run build