
name: "Trivy Scanning - Action"

on:
  workflow_dispatch:
  # push:
  #   branches: [ master, develop ]
  # pull_request:
  #   branches: [ master, develop ]
  # schedule:
  #   - cron: "30 1 * * 0"

jobs:
  Trivy-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm

      - name: Build an image from Dockerfile
        run: |
          npm ci
          cd ./packages/backend-app
          npm run build:match-make
          docker build -t gbraver-burst/backend-app:${{ github.sha }} -f matchMake.Dockerfile .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "gbraver-burst/backend-app:${{ github.sha }}"
          format: "sarif"
          output: "trivy-results.sarif"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"